"""Add indexes

Revision ID: 675f777e1c7f
Revises: e03e205b523f
Create Date: 2025-12-31 16:01:20.664575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675f777e1c7f'
down_revision = 'e03e205b523f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
