"""Add columns to users

Revision ID: e03e205b523f
Revises: 6b061c3d0dec
Create Date: 2025-12-31 16:00:21.122219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e03e205b523f'
down_revision = '6b061c3d0dec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
